### ISSUE TITLE
Problem with Not unique table/alias

### ISSUE THREAD

**Issue by svadim-21** [ProAI/eloquent-versioning#4]
```
I have some problem with this code:
Syntax error or access violation: 1066 Not unique table/alias: 'orders_version' (SQL: select * from `orders` inner join `orders_version` on `orders`.`id` = `orders_version`.`ref_id` and `orders_version`.`version` = 1 inner join `orders_version` on `orders`.`id` = `orders_version`.`ref_id` and `orders_version`.`version` = `orders`.`latest_version` where `orders`.`id` = 1 limit 1)
My Schema:
  Schema::create('orders', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->morphs('import');
            $table->integer('latest_version');

            $table->integer('user_id')->nullable()->comment("Id usera");
            $table->integer('orderid_pp')->nullable();

            $table->integer('shop_id')->nullable();
            $table->integer('shop_revision')->nullable();

            $table->timestamp('action_at')->comment("дата клика");

            $table->timestamp('created_at');

            $table->index('orderid_pp');
            $table->index('shop_id');
            $table->engine = 'InnoDB';
        });

        Schema::create('orders_version', function (Blueprint $table) {
            $table->bigIncrements('revid');
            $table->integer('ref_id')->unsigned();
            // $table->integer('ref_id')->primary();
            $table->integer('version')->unsigned();

            $table->string('status', 20)->nullable()->comment("cтатус");

            $table->integer('order_card')->nullable();
            $table->string('order_card_cur', 11)->nullable();

            $table->integer('earning')->nullable());
            $table->string('earning_cur', 11)->nullable();

            $table->integer('cashback_total')->nullable()->comment("");
            $table->integer('cashback_subtotal')->nullable()->comment("");
            $table->string('cashback_cur', 11)->nullable();

            $table->timestamp('updated_at');
            $table->timestamp('deleted_at');
            $table->timestamp('approved_at')->nullable();

            $table->engine = 'InnoDB';
            $table->index('status');
            $table->index('order_card_cur');
            $table->index('earning_cur');
            $table->index('cashback_cur');
        });

My model:

<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    use \ProAI\Versioning\Versionable;
    // use \ProAI\Versioning\SoftDeletes;

    public $timestamps = true;
    public $versioned  = [
        'status',
        'order_card',
        'order_card_cur',
        'earning',
        'earning_cur',
        'cashback_total',
        'cashback_subtotal',
        'cashback_cur',
        'updated_at',
        'deleted_at',
        'approved_at',
    ];

}
Select:
$order = Order::version(1)->find(1);
 dd($order->toArray());

Olso i have problem with 
 $order = Order::allVersions()->get();
       sd($order->toArray());
I have exeption:
SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias: 'orders_version' (SQL: select * from `orders` inner join `orders_version` on `orders`.`id` = `orders_version`.`ref_id` inner join `orders_version` on `orders`.`id` = `orders_version`.`ref_id` and `orders_version`.`version` = `orders`.`latest_version`)

Can you help me fix this problem ?




```

**Comment by svadim-21** [comment]
```
I have some problem with this code:
Syntax error or access violation: 1066 Not unique table/alias: 'orders_version' (SQL: select * from `orders` inner join `orders_version` on `orders`.`id` = `orders_version`.`ref_id` and `orders_version`.`version` = 1 inner join `orders_version` on `orders`.`id` = `orders_version`.`ref_id` and `orders_version`.`version` = `orders`.`latest_version` where `orders`.`id` = 1 limit 1)
My Schema:
  Schema::create('orders', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->morphs('import');
            $table->integer('latest_version');

            $table->integer('user_id')->nullable()->comment("Id usera");
            $table->integer('orderid_pp')->nullable();

            $table->integer('shop_id')->nullable();
            $table->integer('shop_revision')->nullable();

            $table->timestamp('action_at')->comment("дата клика");

            $table->timestamp('created_at');

            $table->index('orderid_pp');
            $table->index('shop_id');
            $table->engine = 'InnoDB';
        });

        Schema::create('orders_version', function (Blueprint $table) {
            $table->bigIncrements('revid');
            $table->integer('ref_id')->unsigned();
            // $table->integer('ref_id')->primary();
            $table->integer('version')->unsigned();

            $table->string('status', 20)->nullable()->comment("cтатус");

            $table->integer('order_card')->nullable();
            $table->string('order_card_cur', 11)->nullable();

            $table->integer('earning')->nullable());
            $table->string('earning_cur', 11)->nullable();

            $table->integer('cashback_total')->nullable()->comment("");
            $table->integer('cashback_subtotal')->nullable()->comment("");
            $table->string('cashback_cur', 11)->nullable();

            $table->timestamp('updated_at');
            $table->timestamp('deleted_at');
            $table->timestamp('approved_at')->nullable();

            $table->engine = 'InnoDB';
            $table->index('status');
            $table->index('order_card_cur');
            $table->index('earning_cur');
            $table->index('cashback_cur');
        });

My model:

<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    use \ProAI\Versioning\Versionable;
    // use \ProAI\Versioning\SoftDeletes;

    public $timestamps = true;
    public $versioned  = [
        'status',
        'order_card',
        'order_card_cur',
        'earning',
        'earning_cur',
        'cashback_total',
        'cashback_subtotal',
        'cashback_cur',
        'updated_at',
        'deleted_at',
        'approved_at',
    ];

}
Select:
$order = Order::version(1)->find(1);
 dd($order->toArray());

Olso i have problem with 
 $order = Order::allVersions()->get();
       sd($order->toArray());
I have exeption:
SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias: 'orders_version' (SQL: select * from `orders` inner join `orders_version` on `orders`.`id` = `orders_version`.`ref_id` inner join `orders_version` on `orders`.`id` = `orders_version`.`ref_id` and `orders_version`.`version` = `orders`.`latest_version`)

Can you help me fix this problem ?




```

**Comment by svadim-21** [comment]
Sorry i closed this problem by chance

**Comment by chriscarpenter12** [comment]
@svadim-21 I opened a pull request #8 to fix this issue. I noticed I had it too.

**Comment by markusjwetzel** [comment]
Thanks for the pull request, I've merged it. So this issue can be closed.

**Comment by cbzink** [comment]
Hi,

I'm still encountering this issue. My code and result are nearly identical to @svadim-21. Laravel 5.6, eloquent-versional v1.0.6, PHP 7.1.15, using MySQL.

**Migration:**

```
        Schema::create('payees', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('latest_version');
            $table->string('shipping_name');
            $table->string('shipping_address');
            $table->string('shipping_city');
            $table->string('shipping_state');
            $table->string('shipping_zip_code');
            $table->timestamps();
        });

        Schema::create('payees_version', function(Blueprint $table) {
            $table->integer('ref_id');
            $table->integer('version');
            $table->string('name');
            $table->string('name_control');
            $table->tinyInteger('type_of_tin');
            $table->string('taxpayer_identification_number');
            $table->string('mailing_address');
            $table->string('city');
            $table->string('state');
            $table->string('zip_code');
            $table->timestamp('updated_at');
        });
```

**Model:**

```
class Payee extends Model
{
    use Versionable;

    public $timestamps = true;

    public $versioned = ['name', 'name_control', 'type_of_tin', 'taxpayer_identification_number', 'mailing_address', 'city', 'state', 'zip_code'];
}
```

**Function:** `App\Payee::version(1)->find(1)->first()`

**Error:**

```
Illuminate\Database\QueryException with message 'SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias: 'payees_version' (SQL: select * from `payees` inner join `payees_version` on `payees`.`id` = `payees_version`.`ref_id` and `payees_version`.`version` = 1 inner join `payees_version` on `payees`.`id` = `payees_version`.`ref_id` and `payees_version`.`version` = `payees`.`latest_version` where `payees`.`id` = 1 limit 1)'
```

**Comment by chriscarpenter12** [comment]
@cbzink Try making the changes to your [VersioningScope.php](https://github.com/ProAI/eloquent-versioning/pull/8/commits/36968a0658201198573c43a7c345b375beab246f). See if that fixes your issue. The commit was reverted suspecting an update issue. I would start looking there. Unfortunately I'm not actively using this any longer.

**Comment by cbzink** [comment]
@chriscarpenter12 Thanks, I rolled back to v1.0.5 and everything seems to be working on the surface.
